version: 2.1

jobs:
  test-dev:
    docker:
      - image: circleci/node:12.16
    environment:
      access_key_id: AKIASSUP2LMID6UIW7FX
      secret_access_key: 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
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm install
      - run: npm test

  deploy-dev:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - run:
          name: Deploy to dev over SSH
          environment:
            AWS_EC2_USER: ec2-user
            AWS_EC2_IP: 18-188-60-40
            AWS_EC2_REGION: us-east-2
          command: ssh -oStrictHostKeyChecking=no $AWS_EC2_USER@ec2-$AWS_EC2_IP.$AWS_EC2_REGION.compute.amazonaws.com /usr/local/bin/backend_deployment_script.sh

workflows:
  deploy-dev-workflow:
    jobs:
      - test-dev
      - deploy-dev:
          requires:
            - test-dev
          filters:
            branches:
              only: dev

